In [1]:
import numpy as np

In [6]:
a = np.array([1,5,10])

print (a)


[ 1  5 10]


In [7]:
b = np.array([[1,7,20],[5,8,9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [8]:
b.ndim

2

In [9]:
a.ndim

1

In [10]:
b.shape


(2, 3)

In [11]:
a.dtype

dtype('int32')

In [12]:
x = np.array([1.0,3.2,4.5])
x.dtype

dtype('float64')

In [13]:
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [14]:
b[0,2]

20

In [15]:
b[1,1]

8

In [16]:
b[0]

array([ 1,  7, 20])

In [17]:
b[0,1:]

array([ 7, 20])

In [19]:
b[1,1] = 18
b[1,1]

18

In [20]:
b

array([[ 1,  7, 20],
       [ 5, 18,  9]])

In [21]:
dizi_s = np.zeros((2,3))
dizi_s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
dizi_s = np.full((4,4),50)
dizi_s

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [24]:
dizi2 = np.random.rand(4,3)
dizi2

array([[0.52342628, 0.54621288, 0.23522518],
       [0.45845311, 0.16027095, 0.60538977],
       [0.53351254, 0.07737084, 0.30277128],
       [0.61647243, 0.27322272, 0.31776024]])

In [27]:
dizi3 = np.random.randint(0,100,size=(5,5))
dizi3


array([[54,  4, 37, 80, 71],
       [63, 98, 50, 45, 39],
       [48,  0, 93, 22, 59],
       [42, 83, 93, 68, 11],
       [16, 55,  0, 24, 65]])

In [29]:
a = np.array([1,2,3])
b = a
b[0] = 90
print(a)

[90  2  3]


In [30]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 90
print (a)

[1 2 3]


In [32]:
dizi4 = np.array([[1,2,3],[4,5,6]])
dizi4

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.min(dizi4)

1

In [34]:
np.max(dizi4)

6

In [35]:
np.sum(dizi4)

21

In [36]:
filedata = np.genfromtxt("Ornek.txt", delimiter = ",")
filedata = filedata.astype("int32")
print(filedata)

[[1 2 3 4 5 6 7]
 [8 9 7 9 9 8 7]
 [3 3 3 5 7 9 0]]


In [37]:
filedata[1,0]

8

In [38]:
filedata[2,3]

5